### ISSUE TITLE
`!show et ;` fails in distribute mode / Byzer-notebook fails to start

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/kolo-lang#1641]
When we run `!show et` in distribute mode (e.g. based on yarn/k8s), this macro function may fails. This will cause 
the byzer-notebook fails to start because the `ETService` relies on this macro function to get all ets.

**Comment by chncaesar** [comment]
Verified in hadoop 2.7.1 (HDP 2.4.0).

**Comment by chncaesar** [comment]
Close as it's pr is merged
