### ISSUE TITLE
The path is lack of home prefix  in ML Model explanation

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/kolo-lang#1649]
We can use datasource modelExplain to show info from some model like
following:

```sql
load modelExplain.`/tmp/model` 
where alg="RandomForest"
as output;
```

However, the implementation for now will ignore HOME PREFIX and VERSION in path `/tmp/model` and then the exception `File /tmp/model does not exist` will throws.

**Comment by chncaesar** [comment]
Working on it
