### ISSUE TITLE
【CI】The script of make-distribution.sh can not support python2.7

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/kolo-lang#1655]
## Description

When I try to execute the script of `make-distribution.sh` I get some exceptions below:

![middle_img_v2_b5321752-fae2-404f-b461-367a245cad8g](https://user-images.githubusercontent.com/20615623/148879048-e080b7f8-d7e5-4362-8caa-241b7afbf601.png)

It is normal in the python3 environment, why is this happening?

**Comment by hellozepp** [comment]
`Type annotations` are not yet supported in python2, we can try to remove them to fix.

**Comment by allwefantasy** [comment]
There is no need to  support python 2.7.  We can detect the python version before other code and if it's 2.7 just show the user message  that python 2.7 is not support .

So you can close this issue and file a new issue that adding the python version checker.
