### ISSUE TITLE
It's better to update dependency javax.mail from version 1.4.7 to 1.6.2.

### ISSUE THREAD

**Issue by AdmondGuo** [byzer-org/kolo-lang#1659]
## Problem
After fix #1658, sending an email will still report an error. Here is the main msg of the Exception:
```
Could not convert socket to TLS
javax.mail.MessagingException: Could not convert socket to TLS;
nested exception is:
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
```
## Root Cause
Debug code and search for exception keywords. It is found that the problem is version dependent.
Current Java Mail version is 1.4.7, and the last update time is 2013. The supported TLS versions are older.
TLS encryption relies on Java.
 The description in the java.security of java8 is:
```
# Example:
#  jdk.tls.disabledAlgorithms=MD5, SSLv3, DSA, RSA keySize < 2048
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
  DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
  include jdk.disabled.namedCurves
```
So when user specifies `properties mail.smtp.starttls.enable` = "true", the program will not find the correct encryption algorithm.
## Solution
1. Add the specified configuration
Add configuration ` properties mail. smtp. ssl. protocols`="TLSv1.2"
The displayed indicates the TLS version.
However, other adaptation problems may still occur in the lower version. The cost explained to users here is relatively large and it is easy to lose user confidence.

2. Update dependency
Update dependency to the latest applicable version 
```
<!-- https://mvnrepository.com/artifact/com.sun.mail/javax.mail -->
<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>javax.mail</artifactId>
    <version>1.6.2</version>
</dependency>
```
can solve the problem without configuration.
Since no other functions depend on this package, I suggest using update dependency to upgrade.
### refer
[[Solved] javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)](https://flutterq.com/javax-net-ssl-sslhandshakeexception-no-appropriate-protocol-protocol-is-disabled-or-cipher-suites-are-inappropriate/#Solution_1_Upgrade_Javamail)
[java.lang.NoClassDefFoundError: com/sun/mail/util/MailLogger javax/mail/MessagingException_柒小柒七的博客-C](https://blog.csdn.net/u013361445/article/details/49663329)

**Comment by chncaesar** [comment]
Close this issue, as PR is merged
