### ISSUE TITLE
byzer  查询结果有可能丢失列

### ISSUE THREAD

**Issue by zuoc** [byzer-org/kolo-lang#1697]
sample data
![image](https://user-images.githubusercontent.com/8666067/154609190-80ada358-f4af-4cca-b738-cf919af40f22.png)

当我使用以下sql查询，并且to_date 函数使用的 pattern 和实际数据格式不匹配时，order date 列会丢失
![image](https://user-images.githubusercontent.com/8666067/154609315-1758214b-9c7a-4a0d-8d37-a48f32b6cb5f.png)

**Comment by allwefantasy** [comment]
改原因是因为全为 null 的列会在json中被舍弃，从而无法渲染到界面上。
