### ISSUE TITLE
byzer-sandbox 的镜像中依然有 mlsql 以及 kolo-lang 相关的 naming

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/kolo-lang#1723]
**替换sandbox镜像中mlsql、kolo-lang的命名为byzer、byzer-lang**

## 涉及范围：
docker 容器中的文件、文件夹
docker容器使用的环境变量

**Comment by ZhengshuaiPENG** [comment]
关联 issue：
- https://github.com/byzer-org/byzer-build/issues/32
- https://github.com/byzer-org/byzer-lang/issues/1678

**Comment by ZhengshuaiPENG** [comment]
注意：需要替换打包脚本中 jdk8 为 Open JDK8
