### ISSUE TITLE
Development help

### ISSUE THREAD

**Issue by st631369677** [byzer-org/kolo-lang#1792]
I clone project from https://github.com/byzer-org/byzer-lang.git , but I can't find maven gpg profile and tech.mlsql.example.app.LocalSparkServiceApp
![image](https://user-images.githubusercontent.com/93751062/175929571-a6f262d8-9735-42c7-bbff-400fae930f75.png)

**Comment by ZhengshuaiPENG** [comment]
Hi @st631369677 , please find [LocalSparkServiceApp Class](https://github.com/byzer-org/byzer-lang/blob/master/streamingpro-mlsql/src/main/java/tech/mlsql/example/app/LoalSparkServiceApp.scala) here
