### ISSUE TITLE
【Bug】byzer执行 impala多表join 使用 directQuery，返回结果都为字段元数据

### ISSUE THREAD

**Issue by freezhou2022** [byzer-org/kolo-lang#1828]
byzer执行 impala多表join 使用 directQuery，返回结果都为字段元数据，没有返回值
![image](https://user-images.githubusercontent.com/105032032/187076033-9597bed0-5e1c-437b-955b-eb25524b4deb.png)

**Comment by ZhengshuaiPENG** [comment]
Relates to https://github.com/byzer-org/byzer-lang/issues/1829

**Comment by freezhou2022** [comment]
impala驱动问题，升级到2.6.28解决
