### ISSUE TITLE
[RestET] 分页请求失败时，可配置为直接报错误或返回部分数据

### ISSUE THREAD

**Issue by chncaesar** [byzer-org/kolo-lang#1840]
目前，分页请求失败时，返回已获取的数据，但不报错。因而，下游Notebook/Cell 正常执行，最终生成脏数据。链路较长时，用户排查非常耗时。

同时为了保持灵活性，我们引入一个参数控制 分页请求失败时处理逻辑。
 `config.page.error.strategy`  默认为 `abort`，返回错误信息，且停止运行。
另可选： `return`  返回已有分页数据，并停止运行。

使用例子：
```

load Rest.`http://mlsql.tech/api` where
`config.connect-timeout`="10s"
and `config.method`="GET"
and `config.retry`="2"
and `header.content-type`="application/json"
and `config.page.next`="http://mlsql.tech/api?cursor={0}&wow={1}"
and `config.page.skip-params`="true"
and `config.page.values`="$.path,$.path2" -- json path
and `config.page.interval`="10ms"
and `config.page.retry`="3"
and `config.page.limit`="100"
and `config.page.error.strategy`="abort"
and `body`='''
{
"query":"b"
}
```

**Comment by ZhengshuaiPENG** [comment]
行为确认：
为了保证默认情况数据的准确性，避免用户执行完之后数据出错， 默认的行为是，只要分页的过程中出现错误，就直接 abort 并报错，需要留下相应的日志信息
- `config.page.error.strategy` 默认值为 `abort` , 不保留数据
- 可选 `skip`, 即对错误页做跳过处理，最后将拉取到的数据进行返回

Abort 的时候需要优化报错信息，增强日志，需要注意留下的信息有

- 每次分页执行的完整 url 为了获得相关的 offset 的start / end 等信息
- 每次分页重试的信息，api url， start、end，重试的次数
- 如果出现错误，需要留下http 状态码和api 的返回错误
- 每次分页的数据落盘时，需要打出 api url ，start，end，获取到的数据行数，写入的临时目录位置
